version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
  - package-ecosystem: 'npm'
    directory: 'lib/nile'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: 'packages/examples'
    schedule:
      interval: 'daily'
  - package-ecosystem: 'npm'
    directory: 'packages/react'
    schedule:
      interval: 'daily'
